version: 2
references:
  filter_master: &filter_master
    filters:
      branches:
        only: master


jobs:
  publish:
    macos:
      xcode: "9.2.0"

    steps:
      - checkout
      - run:
          name: Build and Publish
          command: | 
            npm install
            npm run build
            cd src/webapp
            npm install -g yarn
            yarn
            export CI=false
            yarn run build
            mv build/* ../../dist/
            cd ../..
            npm run mac-publish

  version_validation:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Validate version has no release yet
          command: ./validate_version.sh

                   
workflows:
  version: 2
  publish-pipeline:
    jobs:
      - version_validation
      - publish:
          requires:
            - version_validation
          <<: *filter_master