version: 2
references:
  filter_master: &filter_master
    filters:
      branches:
        only: master


jobs:
  version_validation:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Validate version has no release yet
          command: ./version_tag_exists.sh

  publish:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"

    steps:
      - checkout
      - run:
          name: Build and Publish
          command: | 
            npm install
            npm run build
            cd src/webapp
            npm install -g yarn
            yarn
            export CI=false
            yarn run build
            mv build/* ../../dist/
            cd ../..
            npm run mac-publish

                   
workflows:
  version: 2
  publish-pipeline:
    jobs:
      - publish:
          requires:
          <<: *filter_master