version: 2
jobs:
  publish:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: | 
            # brew update
            # brew install node@8
            # echo 'export PATH="/usr/local/opt/node@8/bin:$PATH"' >> ~/.bash_profile
            # export PATH="/usr/local/opt/node@8/bin:$PATH"
            npm install
            npm run build
            cd src/webapp
            npm install -g yarn
            yarn
            export CI=false
            yarn run build
            mv build/* ../../dist/
            cd ../..
            npm run mac-publish

                   
workflows:
  version: 2
  publish-pipeline:
    jobs:
      - publish 