version: 2
jobs:
  publish:

    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: | 
            brew install node@8
            npm install
            npm run build
            cd src/webapp
            yarn
            yarn run build
            mv build/* ../../dist/
            cd ../..
            npm run mac-publish

                   
workflows:
  version: 2
  publish-pipeline:
    jobs:
      - publish 