export enum IpcChannel {
    POP_CHOOSE_REPOSITORY_MAIN = "pop-choose-repository-main",
    POP_CHOOSE_REPOSITORY = "pop-choose-repository",
    REPOS_REQUEST_MAIN = "repos-request-main",
    REPOS_REQUEST = "repos-request",
    REFRESH_REPOS = "refresh-repos",
    HIDDEN = "hidden",
    START_SERVER_ERROR = "start-server-error",
    GET_USER_ID = "get-user-id",
    GET_PLATFORM = "get-platform",
    FORCE_EXIT = "force-exit",
    INSPECT_ALL = "inspect-all",
    AUTO_LAUNCH_IS_ENABLED_REQ = "auto-launch-is-enabled-req",
    AUTO_LAUNCH_IS_ENABLED_CHANGED = "auto-launch-is-enabled-changed",
    AUTO_LAUNCH_SET = "auto-launch-set",
    INDEX_WORKER_UP = "index-worker-up",
    APP_WINDOWS_UP = "app-window-up",
    INDEXER_WORKER_ID = "indexer-worker-id",
    TRACK = "track",
    MAIN_WINDOW_ID = "main-window-id",
    SPECIFIC_WORKER_INDEX_ID = "specific-worker-index-id",
    APP_REPO = "add-repo",
    DELETE_REPO = "delete-repo",
    EDIT_REPO = "edit-repo",
    CLEAR_ALL_REPOS = "clear-all-repos",
    SET_LOG_LEVEL = "set-log-level",
    EXCEPTION_MANAGER_IS_ENABLED_REQ = "exception-manager-is-enabled-req"
}
